DROP TABLE IF EXISTS usuarios;

DROP TABLE IF EXISTS redes_sociais;

DROP TABLE IF EXISTS portfolios;

DROP TABLE IF EXISTS acessos;

DROP TABLE IF EXISTS comentarios;

DROP TABLE IF EXISTS temas;

DROP TABLE IF EXISTS informacoes;

DROP TABLE IF EXISTS projetos;

DROP TABLE IF EXISTS imagens;